version: "3.1"
services:
  db:
    container_name: obah-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: obah_db_user
      POSTGRES_PASSWORD: obah_db_password
      POSTGRES_DB: obah_db

volumes:
  db_obah_volume:
