version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10

    working_directory: /repo

jobs:
  test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Instanlando dependencias
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Testando a Aplicação
          command: yarn test
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Instanlando dependencias
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Gerando arquivos de Build e Deploy
          command: yarn build
      - persist_to_workspace:
          root: dist
          paths:
            - .
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /dist
      - run:
          name: Install Aws-cli
          command: sudo pip install awscli
      - run:
          name: Deploying
          command: eb deploy ObahApi-env
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
