version: 2.1

executors:
  obah-executor:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

commands:
  deploy:
    description: "Deploy Application to ElasticBeanstalk"
    steps:
      - run:
          name: Atualizando versão de Api
          command: |
            yarn version --patch
            git push origin master
            git push --tags
      - run:
          name: Install Aws-cli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
          filters:
            branches:
              only: master
      - run:
          name: Deploying Api
          command: eb deploy
          filters:
            branches:
              only: master

jobs:
  test:
    executor: obah-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Instanlando dependencias
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Testando a Aplicação
          command: yarn test
  build:
    executor: obah-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Instanlando dependencias
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Gerando arquivos de Build e Deploy
          command: yarn build
      - deploy
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
