version: 2.1

executors:
  obah-executor:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

jobs:
  test:
    executor: obah-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Instanlando dependencias
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Testando a Aplicação
          command: yarn test
  build:
    executor: obah-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Instanlando dependencias
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Gerando arquivos de Build e Deploy
          command: yarn build
      - run:
          name: Deploy Api
          command: |
            if [[ ${CIRCLE_BRANCH} == "master" ]]; then
              echo "It worked!";
            else
              echo "Nope!"; exit 1
            fi
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
